# Generated by Django 3.1.1 on 2020-09-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='http://www.dirtyapronrecipes.com/wp-content/uploads/2015/10/food-placeholder.png', max_length=500),
        ),
    ]
